FROM bennettaur/nginx-http2

COPY ./content/website1 /usr/share/nginx/html
COPY ./configs/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./configs/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./configs/server.crt /etc/nginx/server.crt
COPY ./configs/server.key /etc/nginx/server.key
