FROM ubuntu:xenial

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        wget \
        build-essential \
        ca-certificates \
    && wget https://www.openssl.org/source/openssl-1.0.2j.tar.gz \
	&& tar -xvzf openssl-1.0.2j.tar.gz \
	&& cd openssl-1.0.2j \
	&& ./config \
		--prefix=/usr \
		--openssldir=/usr/ssl \
	&& make clean \
	&& make && make install \
	&& ./config shared \
		--prefix=/usr/local \
		--openssldir=/usr/local/ssl \
	&& make clean \
	&& make \
	&& make install \
    && apt-get install -y \
    	python \
    	python-pip \
    && pip install -U pip

COPY ./http2_client /http2_client

WORKDIR /http2_client

RUN pip install -r dependencies.txt

ENTRYPOINT ["/bin/bash"]
