FROM debian:jessie

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
#RUN groupadd -r www-data && useradd -r --create-home -g www-data www-data

ENV HTTPD_PREFIX /usr/local/apache2
ENV PATH $HTTPD_PREFIX/bin:$PATH
RUN mkdir -p "$HTTPD_PREFIX" \
	&& chown www-data:www-data "$HTTPD_PREFIX"
WORKDIR $HTTPD_PREFIX

# install httpd runtime dependencies
# https://httpd.apache.org/docs/2.4/install.html#requirements
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		libapr1 \
		libaprutil1 \
		libaprutil1-ldap \
		libapr1-dev \
		libaprutil1-dev \
		libpcre++0 \
		libssl1.0.0 \
		libxml2-dev \
	&& rm -r /var/lib/apt/lists/*

ENV HTTPD_VERSION 2.4.23
ENV HTTPD_SHA1 5101be34ac4a509b245adb70a56690a84fcc4e7f

# https://issues.apache.org/jira/browse/INFRA-8753?focusedCommentId=14735394#comment-14735394
ENV HTTPD_BZ2_URL https://www.apache.org/dyn/closer.cgi?action=download&filename=httpd/httpd-$HTTPD_VERSION.tar.bz2
# not all the mirrors actually carry the .asc files :'(
ENV HTTPD_ASC_URL https://www.apache.org/dist/httpd/httpd-$HTTPD_VERSION.tar.bz2.asc

# Disable SSLv2
ENV CPPFLAGS "-DOPENSSL_NO_SSL2=1"

# see https://httpd.apache.org/docs/2.4/install.html#requirements
RUN set -x \
	&& buildDeps=' \
		bzip2 \
		ca-certificates \
		gcc \
		libpcre++-dev \
		make \
		wget \
		pkg-config \
		unzip \
		libtool \
		autoconf \
		automake \
		make \
	' \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends $buildDeps \
	&& rm -r /var/lib/apt/lists/*

# Install a newer OpenSSL
RUN wget https://www.openssl.org/source/openssl-1.0.2j.tar.gz \
	&& tar -xvzf openssl-1.0.2j.tar.gz \
	&& cd openssl-1.0.2j \
	&& ./config \
		--prefix=/usr \
		--openssldir=/usr/ssl \
	&& make clean \
	&& make && make install \
	&& ./config shared \
		--prefix=/usr/local \
		--openssldir=/usr/local/ssl \
	&& make clean \
	&& make && make install \
	&& cd .. \
	\
# build the libnghttp library from the git repo
	&& wget -O nghttp2.zip https://codeload.github.com/nghttp2/nghttp2/zip/master \
	&& unzip nghttp2.zip \
	&& cd nghttp2-master \
	&& autoreconf -i \
	&& automake \
	&& autoconf \
	&& ./configure --enable-lib-only \
	&& make \
	&& make install \
	&& cd ..


ENV LDFLAGS="-Wl,-rpath,/usr/local/ssl"
ENV LD_LIBRARY_PATH="/usr/local/lib"
RUN wget -O httpd.tar.bz2 "$HTTPD_BZ2_URL" \
	&& echo "$HTTPD_SHA1 *httpd.tar.bz2" | sha1sum -c - \
# see https://httpd.apache.org/download.cgi#verify
	&& wget -O httpd.tar.bz2.asc "$HTTPD_ASC_URL" \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys A93D62ECC3C8EA12DB220EC934EA76E6791485A8 \
	&& gpg --batch --verify httpd.tar.bz2.asc httpd.tar.bz2 \
	&& rm -r "$GNUPGHOME" httpd.tar.bz2.asc \
	\
	&& mkdir -p src \
	&& tar -xvf httpd.tar.bz2 -C src --strip-components=1 \
	&& rm httpd.tar.bz2 \
	&& cd src \
	\
	&& ./configure \
		--prefix="$HTTPD_PREFIX" \
		--enable-mods-shared=reallyall \
		--enable-ssl \
		--enable-http2 \
		--with-ssl=/usr/local/ssl \
	&& make -j"$(nproc)" \
	&& make install \
	\
	&& cd .. \
	&& rm -r src \
	\
	&& sed -ri \
		-e 's!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g' \
		-e 's!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g' \
		"$HTTPD_PREFIX/conf/httpd.conf" \
	\
	&& wget https://www.modsecurity.org/tarball/2.9.1/modsecurity-2.9.1.tar.gz \
	&& tar -zxf modsecurity-2.9.1.tar.gz \
	&& cd modsecurity-2.9.1 \
	&& ./configure \
	&& make && make install \
	&& apt-get purge -y --auto-remove $buildDeps

RUN wget https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz \
	&& tar -zxf Python-2.7.11.tgz \
	&& cd Python-2.7.11/ \
	&& ./configure \
	&& make \
	&& make install

COPY ./configs/apache2/mod_evasive24.c "$HTTPD_PREFIX"/mod_evasive24.c
RUN /usr/local/apache2/bin/apxs -cia "$HTTPD_PREFIX"/mod_evasive24.c

COPY ./configs/apache2/httpd-foreground /usr/local/bin/

EXPOSE 443
CMD ["httpd-foreground"]
